name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main

env:
  IMAGE_NAME: minha-api

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Criar imagem Docker
        run: docker build -t ${{ env.IMAGE_NAME }} .

  deploy_homolog:
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Deploy Homologação
        run: echo "Deploy HOMOLOG realizado"

  deploy_producao:
    needs: build
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main'

    environment:
      name: production

    steps:
      - name: Deploy Produção
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

        run: |
          echo "Conectando ao servidor..."
          echo "Deploy PRODUÇÃO realizado"
